[tool.black]
line-length = 99
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | env
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
src_paths = ['fastcontour', 'tests']
skip_glob = ['setup.py']
line_length = 99
lines_after_imports = 2
force_single_line = 'True'
force_sort_within_sections = 'True'
order_by_type = 'False'

[tool.mypy]
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
strict_equality = true
strict_concatenate = true

ignore_missing_imports = true
exclude = [
  '.vscode',
  'build',
  'dist',
  'env',
  'examples'
]
