name: `Code format`

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Build binary
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Install Python dependencies
      run: |
        pip install --upgrade black isort flake8 mypy
        pip install .[test]

    - name: Black
      run: black invaders/ --check --diff
    
    - name: Flake8
      run: flake8 invaders/

    - name: Isort
      run: isort invaders/ --check --diff

    - name: Mypy
      run: mypy invaders/
